#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


NOCOLOR='\033[0m'
Black='\033[0;30m'
DarkGray='\033[1;30m'
Red='\033[0;31m'
LightRed='\033[1;31m'
Green='\033[0;32m'
LightGreen='\033[1;32m'
BrownOrange='\033[0;33m'
Yellow='\033[1;33m'
Blue='\033[0;34m'
LightBlue='\033[1;34m'
Purple='\033[0;35m'
LightPurple='\033[1;35m'
Cyan='\033[0;36m'
LightCyan='\033[1;36m'
LightGray='\033[0;37m'
White='\033[1;37m'

echo "${Cyan}=========================================================${NOCOLOR}"
echo "${Cyan}                   STARTING PRE-COMMIT                   ${NOCOLOR}"
echo "${Cyan}=========================================================\n${NOCOLOR}"

echo "${Yellow}.....................INSTALL PACKAGES....................${NOCOLOR}\n"
npm install

echo "\n${Yellow}......................AUDIT PACKAGES.....................${NOCOLOR}\n"
npm audit

echo "\n${Yellow}.......................CLEAR DIRT........................${NOCOLOR}"
npm run clear:dirt

echo "\n${Yellow}....................PRETTIER CHECKING....................${NOCOLOR}"
npm run format

echo "\n${Yellow}...................TYPESCRIPT CHECKING...................${NOCOLOR}"
npm run check

echo "\n${Yellow}...................ESLINT CHECKING.......................${NOCOLOR}"
npm run lint

echo "\n${Yellow}.....................BUILDING APP........................${NOCOLOR}"
npm run build


echo "\n${Yellow}...............UNIT TEST AND COVERAGE....................${NOCOLOR}"
npm run jest:coverage



echo "\n${Cyan}=========================================================${NOCOLOR}"
echo "${Cyan}                END PRE-COMMIT                           ${NOCOLOR}"
echo "${Cyan}=========================================================${NOCOLOR}"
